apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }} 
spec:
  ports:
  - port: {{ .Values.port } }
    targetPort: {{ .Values.port }}
  selector:
    app: guestbook-ui
  type: LoadBalancer

